name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
          - 27.1
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: './run-tests.sh'
